### ISSUE TITLE
Unable to open database file with gnomAD_DB()

### ISSUE THREAD

**Issue by PabloRomanjo** [KalinNonchev/gnomAD_MAF#13]
Hi,

I'm trying to open gnomad 2.1.1 database, however it returns the **OperationalError: unable to open database file**.

Using Atom in Windows 10. See enclosed image.

https://ibb.co/9qz9DXY

Thanks!

**Comment by PabloRomanjo** [comment]
Solved it. The solution is just to rename the downloaded file to gnomad_db.sqlite3.

**Comment by KalinNonchev** [comment]
Hello Pablo,

have you downloaded the package as:
```python
from gnomad_db.database import gnomAD_DB
download_link = "https://zenodo.org/record/5045102/files/gnomad_db_v2.1.1.sqlite3.gz?download=1"
output_dir = "test_dir" # database_location
gnomAD_DB.download_and_unzip(download_link, output_dir)
```
or manually from the zenodo website? 
The function `gnomAD_DB.download_and_unzip` should have taken care about the name of the sqlite3 file.

Best,
Kalin
